blank_issues_enabled: false
contact_links:
  - name: 🦓 General Zebra Issues & Questions
    url: https://github.com/ZcashFoundation/zebra
    about: "For general Zebra issues, bugs, and questions, please use the upstream repository. This fork is only for Crosslink-specific issues."
  - name: 🔗 Zebra Discussions
    url: https://github.com/ZcashFoundation/zebra/discussions
    about: "Ask questions and discuss Zebra development in the upstream discussions"
  - name: 💬 Zcash Community Support
    url: https://forum.zcashcommunity.com/
    about: "General questions about the Zcash ecosystem and community"
