name: Deploy mdBook site to Pages

on:
  push:
    branches: [ "main", "ms*" ]

  pull_request:
    branches: [ "main", "ms*" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: blacksmith-8vcpu-ubuntu-2404
    env:
      MDBOOK_VERSION: 0.4.36
      MDBOOK_MERMAID_VERSION: 0.15.0
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      # - name: Install mdBook
      #   run: |
      #     curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf -y | sh
      #     rustup update
      #     cargo install --version ${MDBOOK_VERSION} mdbook
      #     cargo install --version ${MDBOOK_MERMAID_VERSION} mdbook-mermaid
      - uses: nixbuild/nix-quick-install-action@v30
      - uses: nix-community/cache-nix-action@v6
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', 'flake.lock') }}  # yamllint disable-line rule:line-length
          restore-prefixes-first-match: nix-${{ runner.os }}-
          purge: true
          purge-prefixes: nix-${{ runner.os }}-
          purge-created: 86400  # 1 day
          purge-primary-key: never
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Build with Nix
        run: nix build .#zebra-book --print-build-logs
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./result/book/book

  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
